# Generated by Django 4.1.3 on 2023-03-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='rideId',
        ),
        migrations.AddField(
            model_name='proposal',
            name='rideId',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
