# Generated by Django 4.1.3 on 2023-03-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_proposal_rideid_proposal_ridename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='senderName',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
