# Generated by Django 4.1.3 on 2023-04-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_ride_latitude_ride_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='deliveryPassword',
            field=models.CharField(blank='True', max_length=10, null='True'),
            preserve_default='True',
        ),
    ]
