# Generated by Django 4.1.3 on 2023-04-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_proposal_deliverypassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='location',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ridePlateNumber',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ridePlateNumberImage',
        ),
    ]
