# Generated by Django 4.1.3 on 2023-04-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_location_ride_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='amount',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='riderPhoneNumber',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='senderPhoneNumber',
            field=models.CharField(default='empty', max_length=20),
        ),
    ]
