# Generated by Django 4.1.3 on 2023-05-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
