# Generated by Django 4.1.3 on 2023-05-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_user_ninslip_user_address_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='formerAmount',
            field=models.TextField(blank=True, null=True),
        ),
    ]
