# Generated by Django 4.1.3 on 2023-05-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_proposal_formeramount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fund_wallet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
